import torch
a=torch.randn(2,3)
b=torch.randn(2,3)
print("Tensor a:")
print(a)
print("Tensor b:")
print(b)
print("Tensor a+b:")
print(a+b)
print("Tensor a-b:")
print(a-b)
print("Tensor a*b:")
print(a*b)
print("Tensor a/b:")
print(a/b)
print("Tensor a^2:")
print(a**2)
print("Tensor a@b:")
print(a@b.T)