import torch
A=torch.randn(3,4)
B=torch.randn(3,4)
print("A+B")
print(A+B)
print("A*B")
print(A*B)
print("A/B")
print(A/B)
print("Trung bình theo cột A:")
print(torch.mean(A, dim=0))
print("Trung bình theo cột B:")
print(torch.mean(B, dim=0))
print("Độ lệch theo cột A:")
print(torch.std(A, dim=0))
print("Độ lệch theo cột B:")
print(torch.std(B, dim=0))
